### PR TITLE
Added missing CPACK lines to create .deb package using "make package"

### PR DESCRIPTION
**Pull request by stephanecharette**
When using Debian or Ubuntu based Linux distro, run "make package" to create the .deb installation file.

- [X] Checked coding [style](https://github.com/pdfmm/pdfmm/blob/master/CODING-STYLE.md)
- [X] Accept to license the code under the terms of the [LGPL 2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html)
- [X] Added attribution in [AUTHORS.md](https://github.com/pdfmm/pdfmm/blob/master/AUTHORS.md)

### CODE REVIEW

**Comment by ceztko** [comment]
I don't know too much about deb packet generation but I [commited](https://github.com/pdfmm/pdfmm/commit/7dbd68fc3c339ca16dca589af89ee4b8a034015c) it with a grain of salt because your changes would side effect all platforms, and that's not what we want to do in Windows/mac/etc.

**Comment by ceztko** [comment]
When soon this project will be moved back to PoDoFo we will understand there what to do with packetization.

**Comment by stephanecharette** [comment]
I don't think all of that is necessary.  On Windows, CPACK use NSIS to create the .exe installer.  And Mac uses...whatever Mac uses, I forget the name.  But the CPACK generators take care of all of this.

**Comment by ceztko** [comment]
Your change was really enforcing "DEB" for all platforms, and that's not the way Debian/Ubuntu maintainers crafted the deb packages anyway. Also consider: at the moment I don't want a default "PACKAGE" target, even it doesn't run with ALL. If you suggest a better **opt-in** way to enable the packetization (for all platforms, not only Linux/deb) that looks better to you please suggest it here. Otherwise maybe better revert the change and discuss it later: I can change my mind later, I'm really busy into the pdfmm -> PoDoFo stuff.

**Comment by stephanecharette** [comment]
That's fine, feel free to disregard the change, I didn't mean to impose anything.  For the moment, we've decided to use libpoppler instead.  I was simply evaluating pdfmm a few months ago which is when I noticed the few simple lines needed to create an installable package.  Certainly makes it easier to people to install, upgrade, and remove when the package manager can be leveraged.

**Comment by ceztko** [comment]
I convinced myself that enabling packaging by default is not that bad and I [committed](https://github.com/pdfmm/pdfmm/commit/8cf7c6ad869f503bed25ec8ec4a1323a95ac5c6a) it once again unconditionally. I just removed setting the `CPACK_GENERATOR` to `DEB` since that was causing to create a deb files also on Windows. Now the packaging format will be the one decided by CMake, hoping it does a good default choice depending on the actual OS (example deb on Debian/Ubuntu, RPM on Fedora/RH/CentOS).

**Comment by stephanecharette** [comment]
Note that you need more options to generate a .exe with NSIS on Windows, etc.  The .deb one is simple.  Here is how I set things up to generate a .exe installer on Windows:  https://github.com/stephanecharette/DarkHelp/blob/master/CM_package.cmake

That example is probably more complicated than it needs to be, but it should give you an idea of what is needed.

**Comment by ceztko** [comment]
I would be much more interested if it produced a MSI package by default in Windows, to make it more agnostic/standard. It seems to be possible with WIX generator. https://cmake.org/cmake/help/latest/cpack_gen/wix.html . I will experiment with that later.

**Pull request closed without merging**
